"""
Build the embeddable /embed/<slug>.html versions of Kibbo calculators, plus /embed/embed.css.

The embed is EXTRACTED from each calculator's own page, never hand-copied:
  - the calculator markup  = the inner HTML of <main class="section-main"> (minus the page's own
                             "Embed this calculator" block, if present)
  - the calculator logic   = the page's final inline <script> (the one after </footer>)
  - page-specific CSS      = the page's own inline <style> block in <head>, if it has one
  - shared CSS             = every rule in /styles.css whose selector contains ".calc-", plus the
                             design tokens those rules use, written to /embed/embed.css

Stripped: nav, page hero, newsletter, footer, cookie-consent.js (and the Google Analytics it loads),
newsletter-signup.js, kibbo-navbar.js, JSON-LD structured data, and the full styles.css.

Links that would otherwise navigate *inside* the iframe get target="_top" (internal links, plus any
URL listed in TOP_LINKS). External helper links that already open in a new tab are left alone.

Re-run this after editing any source calculator:   py -3 scripts/build-embeds.py
Embed pages are noindex and must never be added to sitemap.xml or search-index.json.
"""
import html
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = 'https://www.getkibbo.com'

CALCS = [
    # (embed slug, source page path without .html, calculator name used for attribution)
    ('flight-delay-compensation-calculator', 'flights-travel/calculators/flight-delay-compensation-calculator', 'Flight Delay Compensation Calculator'),
    ('real-discount-calculator', 'shopping-ecommerce/calculators/real-discount-calculator', 'Real Discount Calculator'),
    ('rent-increase-calculator', 'housing-rentals/calculators/rent-increase-calculator', 'Rent Increase Calculator'),
]
# External links that must also leave the iframe for the top window (instead of a new tab).
TOP_LINKS = {'https://airconsumer.dot.gov/escomplaint/ContactUs.aspx'}
TOKENS = ['--bg', '--bg-card', '--text-primary', '--text-secondary', '--text-muted', '--border',
          '--accent-green', '--accent-terra', '--radius-sm', '--font-serif', '--font-sans', '--transition']
FONTS = 'https://fonts.googleapis.com/css2?family=Syne:wght@400;500;600;700;800&family=Inter:wght@300;400;500;600&display=swap'


def read(p):
    return io.open(os.path.join(ROOT, p), encoding='utf-8').read()


def write(p, s):
    full = os.path.join(ROOT, p)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    io.open(full, 'w', encoding='utf-8', newline='\n').write(s)


# ---------------------------------------------------------------- CSS
def css_blocks(css):
    """Yield (prelude, body) for every top-level block, keeping @media blocks whole."""
    i, depth, start = 0, 0, 0
    css = re.sub(r'/\*.*?\*/', '', css, flags=re.S)
    for j, ch in enumerate(css):
        if ch == '{':
            if depth == 0:
                prelude_start = start
                brace = j
            depth += 1
        elif ch == '}':
            depth -= 1
            if depth == 0:
                yield css[prelude_start:brace].strip(), css[brace + 1:j]
                start = j + 1


def build_css():
    css = read('styles.css')
    root = re.search(r':root\s*\{(.*?)\}', css, re.S).group(1)
    tokens = {m.group(1): m.group(2).strip() for m in re.finditer(r'(--[a-z-]+)\s*:\s*([^;]+);', root)}
    missing = [t for t in TOKENS if t not in tokens]
    assert not missing, f'tokens missing from styles.css :root: {missing}'
    rules = []
    for prelude, body in css_blocks(css):
        if prelude.startswith('@media'):
            inner = [f'  {p} {{{b.strip()}}}' for p, b in css_blocks(body) if '.calc-' in p]
            if inner:
                rules.append(prelude + ' {\n' + '\n'.join(inner) + '\n}')
        elif '.calc-' in prelude:
            rules.append(f'{prelude} {{ {" ".join(body.split())} }}')
    used = set(re.findall(r'var\((--[a-z-]+)\)', '\n'.join(rules)))
    assert used <= set(TOKENS), f'.calc-* rules use tokens not in TOKENS: {used - set(TOKENS)}'
    out = ['/* GENERATED by scripts/build-embeds.py from /styles.css — do not edit by hand. */',
           ':root {'] + [f'  {t}: {tokens[t]};' for t in TOKENS] + ['}', '',
           '* { margin: 0; padding: 0; box-sizing: border-box; }',
           'body { font-family: var(--font-sans); background: var(--bg); color: var(--text-primary); -webkit-font-smoothing: antialiased; }',
           'a { color: inherit; text-decoration: none; }',
           'img { max-width: 100%; display: block; }',
           '',
           '/* Embed frame */',
           '.embed-wrap { max-width: 600px; margin: 0 auto; padding: 24px 20px 20px; }',
           '.embed-title { font-family: var(--font-serif); font-size: 22px; font-weight: 700; letter-spacing: -0.01em; line-height: 1.25; color: var(--text-primary); margin: 0 0 22px; }',
           '.embed-attrib { margin-top: 28px; padding-top: 14px; border-top: 1px solid var(--border); font-size: 13px; color: var(--text-muted); }',
           '.embed-attrib a { color: var(--accent-green); font-weight: 600; }',
           '.embed-attrib a:hover { text-decoration: underline; }',
           '',
           '/* Calculator toolkit — every .calc-* rule from /styles.css */'] + rules
    write('embed/embed.css', '\n'.join(out) + '\n')
    return len(rules)


# ---------------------------------------------------------------- links
def fix_links(text):
    """Add target="_top" to internal links (href="/...") and TOP_LINKS, in markup and in JS strings."""
    def repl(m):
        tag = m.group(0)
        href = m.group('href')
        if href.startswith('/') or href in TOP_LINKS:
            tag = re.sub(r'\s+target="[^"]*"', '', tag)
            tag = re.sub(r'\s+rel="[^"]*"', '', tag)
            tag = tag[:-1] + ' target="_top">'
        return tag
    return re.sub(r'<a\s[^>]*href="(?P<href>[^"]+)"[^>]*>', repl, text)


# ---------------------------------------------------------------- pages
def build_page(slug, src, name):
    s = read(src + '.html')
    main = re.search(r'<main class="section-main">(.*?)</main>', s, re.S).group(1)
    main = re.sub(r'\s*<details class="embed-share".*?</details>', '', main, flags=re.S)   # the page's own embed UI
    tail = s[s.index('</footer>'):]
    scripts = re.findall(r'<script>\n(.*?)\n</script>', tail, re.S)
    assert len(scripts) == 1, f'{src}: expected exactly one inline calculator <script> after </footer>, found {len(scripts)}'
    head = s[:s.index('</head>')]
    styles = re.findall(r'<style>\n(.*?)\n</style>', head, re.S)
    hero = re.search(r'<h1 class="section-title">(.*?)</h1>', s, re.S).group(1)
    title_text = html.unescape(re.sub(r'<[^>]+>', '', hero)).strip()
    page_url = f'{SITE}/{src}'

    main_fixed, js_fixed = fix_links(main), fix_links(scripts[0])
    page_style = f'<style>\n{styles[0]}\n</style>\n' if styles else ''
    out = f'''<!DOCTYPE html>
<html lang="en">
<head>
<!-- GENERATED by scripts/build-embeds.py from /{src}.html — do not edit by hand. -->
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<meta name="robots" content="noindex, nofollow">
<title>{html.escape(name)} — Kibbo</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="{FONTS}">
<link rel="stylesheet" href="/embed/embed.css">
{page_style}</head>
<body>
<div class="embed-wrap">
  <h1 class="embed-title">{html.escape(title_text)}</h1>
{main_fixed.strip(chr(10))}
  <p class="embed-attrib"><a href="{page_url}" target="_top">Full calculator &amp; more tools at Kibbo →</a></p>
</div>
<script>
{js_fixed}
</script>
<script>
/* Embed auto-height: tells the host page this document's height, so the iframe grows when a result appears.
   The host's snippet only accepts these messages from https://www.getkibbo.com. */
(function () {{
  var last = 0;
  function report() {{
    var h = Math.ceil(document.documentElement.getBoundingClientRect().height);
    if (h !== last && window.parent !== window) {{ last = h; window.parent.postMessage({{ kibboEmbedHeight: h }}, '*'); }}
  }}
  if (window.ResizeObserver) new ResizeObserver(report).observe(document.documentElement);
  window.addEventListener('load', report);
  report();
}})();
</script>
</body>
</html>
'''
    write(f'embed/{slug}.html', out)
    return len(re.findall(r'target="_top"', main_fixed + js_fixed))


if __name__ == '__main__':
    n_rules = build_css()
    print(f'embed/embed.css: {n_rules} .calc-* rules, {len(TOKENS)} tokens')
    for slug, src, name in CALCS:
        n_top = build_page(slug, src, name)
        print(f'embed/{slug}.html  <- /{src}.html  ({n_top} link(s) set to target="_top")')
